apiVersion: v1
kind: Service
metadata:
  name: broker-api-service
  namespace: optalpha-deployment
spec:
  selector:
    app: broker-api
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
      nodePort: 30001
  type: NodePort
